In [2]:
import pandas as pd
from pathlib import Path

In [3]:
RAW_FILE = "../data/raw/gene_info"
SAVE_FILE = "../data/processed/gene_info_filtered.csv"

In [4]:
import os

size = os.path.getsize(RAW_FILE) / (1024**3)
print(f"File size: {size:.2f} GB")

File size: 8.93 GB

In [5]:
chunksize = 500000

filtered_chunks = []

for chunk in pd.read_csv(
        RAW_FILE,
        sep="\t",
        chunksize=chunksize,
        dtype=str,
        low_memory=False):

    # filter human genes
    chunk = chunk[chunk["#tax_id"] == "9606"]

    # keep only useful columns
    chunk = chunk[[
        "GeneID",
        "Symbol",
        "description"
    ]]

    filtered_chunks.append(chunk)

In [6]:
gene_df = pd.concat(filtered_chunks, ignore_index=True)

print("Total human genes:", len(gene_df))
gene_df.head()

Total human genes: 193791

  GeneID Symbol                     description
0      1   A1BG          alpha-1-B glycoprotein
1      2    A2M           alpha-2-macroglobulin
2      9   NAT1           N-acetyltransferase 1
3     10   NAT2           N-acetyltransferase 2
4     11   NATP  N-acetyltransferase pseudogene

In [7]:
gene_df.to_csv(SAVE_FILE, index=False)

print("Saved:", SAVE_FILE)

Saved: ../data/processed/gene_info_filtered.csv

In [8]:
gene_df.info()
gene_df.sample(5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 193791 entries, 0 to 193790
Data columns (total 3 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   GeneID       193791 non-null  object
 1   Symbol       193791 non-null  object
 2   description  193791 non-null  object
dtypes: object(3)
memory usage: 4.4+ MB

,GeneID,Symbol,description
165284,129998399,LOC129998399,ATAC-STARR-seq lymphoblastoid silent region 18164
144975,129660499,LOC129660499,ReSE screen-validated silencer GRCh37_chr1:224...
55107,110120745,LOC110120745,VISTA enhancer hs687
133291,127891293,LOC127891293,H3K4me1 hESC enhancer GRCh37_chr19:35761221-35...
177581,130055721,LOC130055721,ATAC-STARR-seq lymphoblastoid active region 8440